"""instance tester in seed file

Revision ID: fd36536134dd
Revises: 70b2d1525f1e
Create Date: 2023-12-26 17:12:17.096989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd36536134dd'
down_revision = '70b2d1525f1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
